### PR TITLE
Bump version 0.4.0

### PR DESCRIPTION
**Pull request by uilianries**
As glog is present in Conan Center, we need to wait for libunwind before to merge this new version.

If you run ldd on Linux, you will see libunwind as glog requirements.

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries what exactly do we need to wait from libunwind?

**Comment by uilianries** [comment]
Oh sorry, libunwind is not in Conan Center. As glog is approved in Conan Center, we can't add a new dependency which won't be find by conan-center.

**Comment by SSE4** [comment]
we may add with False by default, right?

**Comment by uilianries** [comment]
Where? we don't have an option for libunwind. Glog's Cmake runs `find_library`, which doesn't use any cmake option to include libunwind.

**Comment by SSE4** [comment]
oh, this is unfortunate

**Comment by uilianries** [comment]
well, we could add one by patching. I think libunwind is optional. WDYT?

**Comment by SSE4** [comment]
I wouldn't be so sure it's optional if their CMake doesn't have an option to disable it.
does anything prevent us from inclusion of libundind into conan-centre?

**Comment by uilianries** [comment]
No, just waiting for the inclusion review.

**Comment by SSE4** [comment]
ping @danimtb

**Comment by danimtb** [comment]
libunwind review done. It will be in conan center once the issues are solved: https://github.com/bincrafters/conan-libunwind/pull/1

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
