### PR TITLE
Testing/0.3.5

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by SSE4** [comment]
failed because of gflags were built with newer glibc. I am triggering rebuild of gflags.

**Comment by SSE4** [comment]
also, has stalled CircleCI configuration, will remove it later

**Comment by SSE4** [comment]
hm, also gflags needs Clang 9.1 as well, please make PR for it

**Comment by uilianries** [comment]
Thanks! I don't know why github is using Circle CI on check steps, because we dont have circle ci support anymore on this project.

**Pull request merged**
