### PR TITLE
split builds and CI updates

### PR DESCRIPTION
**Pull request by sigmoidal**
This PR fixes a number of issues related to split builds.

It improves:

a) The syntax required in the appveyor.yml is now much simpler (no need to specify Debug/Release per config in the matrix)
b) the build.py generates split builds per build_type (release/debug), but also supports user-overriding through the respective conan env variables. 
c) It creates three levels of remote repository dependency lookups in an order that allows users to override at will:
    1) the user's auto-generated (like before): "https://api.bintray.com/conan/{username}/public-conan"
    2) the bincrafters' bintray repo next: https://api.bintray.com/conan/bincrafters/public-conan
    3) any repos specified through CONAN_REMOTES, which are prepended to the abovementioned repos.

Note that without this approach forking repos like conan-glog and using CI fails if the bincrafters' bintray remote is not added manually. This PR fixes all these.

### CODE REVIEW

**Comment by DariuszOstolski** [comment]
LGTM

**Review by ghost — APPROVED** [review]
Great idea! I think we should publish this.

**Comment by SSE4** [comment]
seems like we have lost this one out of our attention. needs rebase.

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
